---

all:
  hosts:
    local1:
      ansible_user: ubuntu
      ansible_host: 23.20.249.98
  vars_files:
    - inventories/ccc_prod/group_vars/superset/vars.yml
    - inventories/ccc_prod/group_vars/superset/vault.yml
  vars:
    env: ccc_prod
...
